### ISSUE TITLE
Text formatting

### ISSUE THREAD

**Issue by vico93** [isXander/main-menu-credits#13]
Sorry the newbie question, but is possible - and if yes, how - to apply text formatting (the ones supported by Minecraft) on each line?

Tried to paste the `/tellraw` json argument but it doesn't worked.

**Comment by isXander** [comment]
Could you say exactly what you pasted in the JSON?

**Comment by vico93** [comment]
Seems like its related to #14 - just me struggling to figure out how to use the mod. Sorry about that.
