### ISSUE TITLE
Cannot add text on bottom left/right on main menu

### ISSUE THREAD

**Issue by vico93** [isXander/main-menu-credits#14]
Tried to add text to the bottom part of the screen on main menu:

```
{
  "main_menu": {
    "top_left": [],
    "top_right": [],
    "bottom_left": ["VicoCraft 1.19.3-0.1 BETA"],
    "bottom_right": ["PS.: Contém BUGS!"],
    "mod_blacklist": []
  },
  "pause_menu": {
    "top_left": [],
    "top_right": [],
    "bottom_left": [],
    "bottom_right": [],
    "mod_blacklist": []
  }
}
```
But none of the lines appear (i though it was to appear above or below those lines).
Putting the text on `top_left` works as intented.

![image](https://user-images.githubusercontent.com/3485505/214688270-2ec1ea58-79a3-4232-b962-030c6c112fa1.png)

**Comment by isXander** [comment]
This is not the format for text.
```json
{
  "main_menu": {
    "top_left": [],
    "top_right": [],
    "bottom_left": [{"text":"VicoCraft 1.19.3-0.1 BETA"}],
    "bottom_right": [{"text":"PS.: Contém BUGS!"}],
    "mod_blacklist": []
  },
  "pause_menu": {
    "top_left": [],
    "top_right": [],
    "bottom_left": [],
    "bottom_right": [],
    "mod_blacklist": []
  }
}
```

**Comment by vico93** [comment]
> This is not the format for text.
> 
> ```json
> {
>   "main_menu": {
>     "top_left": [],
>     "top_right": [],
>     "bottom_left": [{"text":"VicoCraft 1.19.3-0.1 BETA"}],
>     "bottom_right": [{"text":"PS.: Contém BUGS!"}],
>     "mod_blacklist": []
>   },
>   "pause_menu": {
>     "top_left": [],
>     "top_right": [],
>     "bottom_left": [],
>     "bottom_right": [],
>     "mod_blacklist": []
>   }
> }
> ```

Strange. The JSON i was using worked fine on top left...
BTW, if the whole tellraw json is accepted, does it means i can set colors and formatting for each line? Can you give me an example, if possible?

**Comment by isXander** [comment]
I simply use Minecraft's text parsing system. So you would do:
```json
{"text":"VivoCraft 1.19.3-0.1 BETA","color":"red"}
```

**Comment by vico93** [comment]
Sorry the insistence, but how is the proper way to add multi-colored lines via config?

I tried `"bottom_left": ["\u00a76VicoCraft \u00a7f1.19.3-0.1 \u00a7cBETA"],` although it worked clearly isn't the proper way (it needs to be JSON).

**Comment by isXander** [comment]
This is the legacy way to colour text.
