### ISSUE TITLE
Positioning incorrect when running Mod Menu 6.2.0 on Quilt

### ISSUE THREAD

**Issue by iiPythonx** [isXander/main-menu-credits#15]
Running Main Menu Credits 1.1.1 with Mod Menu 6.1.0 generates the expected results:
![correct](https://user-images.githubusercontent.com/35084023/232954062-77742f0e-5790-48d3-bafd-3582961a5b62.png)

However, running Mod Menu 6.2.0 instead generates the following:
![wrong](https://user-images.githubusercontent.com/35084023/232954214-48dabe17-33bb-433b-97e2-254bd0d6d9e4.png)

As you can see, the text is pushed down an extra line.  
From what I can gather, Mod Menu's [`shiftButtons`](https://github.com/TerraformersMC/ModMenu/blob/d8daccda04d0a3ac5bed072dd8ca4bf9e8df504d/src/main/java/com/terraformersmc/modmenu/event/ModMenuEventHandler.java#L112-L117) method is causing the problem, and Main Menu Credits' compatibility layer to prevent said method from calling has stopped working.  

That being said, the only thing that has changed is [adding an `instanceof` check for `ClickableWidgets`](https://github.com/TerraformersMC/ModMenu/commit/d8daccda04d0a3ac5bed072dd8ca4bf9e8df504d#diff-75a7c6795864aa3c7d1ffc5d22c846fd4859ae1c3453ecf62575066f6e61eaddR115).

---

I'm not sure whether to report this here or in the Mod Menu repo, as the problem **seems** to be on their side.

**Comment by RinixGG** [comment]
Can confirm
![изображение](https://user-images.githubusercontent.com/73175330/233857038-ee8ac9a5-dec0-4bb3-80e8-1cb3805046aa.png)

**Comment by iiPythonx** [comment]
Problem was fixed in 1.1.2 (e73b32d), can confirm it's now working @RinixGG.
