### ISSUE TITLE
Incompatibility with Minimal Menu

### ISSUE THREAD

**Issue by RaptaG** [isXander/main-menu-credits#5]
I run Fabulously Optimized alongside with Minimal Menu, which among other things, gives you the ability to hide the Mojang's copyright text, on the bottom right of the screen. If this setting is enabled, then the version of FO is floating, and does not go to the bottom the screen. Could you please fix that?

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/77157639/169643095-1bf6af84-b2c5-4be2-b0c5-3f709477405c.png)

**Comment by isXander** [comment]
Fixed in v1.0.3
