### ISSUE TITLE
[Feature Request:] Add a Config Screen

### ISSUE THREAD

**Issue by StereoMadnessss** [isXander/main-menu-credits#6]
This one is basic and should exist in the mod as the config text might be confusing for people.
I would imagine that a preview would be shown of how it would look like and how it would look. Something to attach a link in a separate box next to your text on that part of the screen would also be welcome.

These are just my ideas and you don't have to add them.

**Comment by isXander** [comment]
This mod isn't really for the end user. It's for modpack or mod developers

**Comment by srnyx** [comment]
Yeah, I'd rather not have a config screen so that people can't easily change the credits.
